### ISSUE TITLE
Can't enter the seed

### ISSUE THREAD

**Issue by jpph** [enteropositivo/seedsigner-emulator#2]
issue discovered in seedsigner-distro, copying it here :
I was trying to enter the seed to convert it to xpub, but right-middle buttons doesn't work, so I can't choose a word.
I'm running it in virtrualbox on mac
video showing the issue:
[seedsigner.webm](https://user-images.githubusercontent.com/155891/178100731-e9c4d5a2-1cf5-451d-9637-03a928108e4f.webm)

original ticket:
https://github.com/jpph/seedsigner-distro/issues/1

**Comment by limpbrains** [comment]
I've tried same thing with seedsigner-emulator installed on Ubuntu, same bug

**Comment by jpph** [comment]
Yes , forgot to tell, I did have same issue in Ubuntu too...

**Comment by enteropositivo** [comment]
Yes, you are right.

I've fixed the bug,    you can replace your   **seedsigner-emulator/seedsigner/emulator/virtualGPIO.py**  for the new one.

**Comment by jpph** [comment]
Yes, working. I have made new build of seedsigner-distro and it is working
Thank you!
